# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Log_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=9)),
                ('scale', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Data_log_Entries',
            },
        ),
        migrations.CreateModel(
            name='Field_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=15)),
                ('measure', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='data_log_entry',
            name='field_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Field_Device'),
        ),
        migrations.AddField(
            model_name='data_log_entry',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Unit'),
        ),
        migrations.AddIndex(
            model_name='data_log_entry',
            index=models.Index(fields=['field_device', 'name', 'time_stamp'], name='main_data_l_field_d_08f636_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='data_log_entry',
            unique_together=set([('field_device', 'name', 'time_stamp')]),
        ),
        migrations.AlterOrderWithRespectTo(
            name='data_log_entry',
            order_with_respect_to='field_device',
        ),
    ]
