# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180501_2008'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='data_log_entry',
            name='main_data_l_field_d_08f636_idx',
        ),
        migrations.AlterUniqueTogether(
            name='data_log_entry',
            unique_together=set([('field_device', 'param_metadata', 'time_stamp')]),
        ),
        migrations.AddIndex(
            model_name='data_log_entry',
            index=models.Index(fields=['field_device', 'param_metadata', 'time_stamp'], name='main_data_l_field_d_118b32_idx'),
        ),
        migrations.RemoveField(
            model_name='data_log_entry',
            name='name',
        ),
    ]
