# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-30 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180503_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_device',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
