# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_field_device_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_metadata',
            name='access',
            field=models.CharField(choices=[('RO', 'Read Only'), ('RW', 'Read Write')], default='RO', max_length=2),
        ),
    ]
